### ISSUE TITLE
with everything blocked, the favicon is still requested and downloaded

### ISSUE THREAD

**Issue by requiredregistration** [futpib/policeman#109]
a website for testing: www.wired.com

**Comment by futpib** [comment]
While playing around this bug I noticed that even when Policeman's `shouldLoad` rejects a favicon request Firefox loads it (checked with Wireshark). Now this will be tricky to solve, since AFAIK `shouldLoad` is the only way to intercept loads.

**Comment by futpib** [comment]
This should be fixed by bd69e1700084b249541bc4de34d7e8a8c803391a.

Thanks for reporting, you actually pointed out a whole class of requests policeman couldn't control. I wonder if RequestPolicy-people solved this, this was not an easy one for me.

**Comment by futpib** [comment]
Opening this by 01f091291ebc2460e02cd3e1b577aab52ff96a5b in favour of #141.

For now (hopefully not for long), this and #141 are mutually exclusive.

**Comment by requiredregistration** [comment]
you are welcome

with the stable version the favicon is requested and downloaded, with the nightly build it is not

**Comment by requiredregistration** [comment]
"requestpolicy continued" has the same problem, testing with wired.com, resources are being requested and downloaded without having permitted that, this with everything set to be blocked by default, only if the user allows something it will be requested

**Comment by futpib** [comment]
@requiredregistration Resources? Do you mean there is anything besides favicon that goes undetected?

**Comment by requiredregistration** [comment]
it allows it requests and downloads js, css, and image files, and that without permission, with everything having been set to be blocked by default in RPC, in PM only favicons are requested and downloaded

**Comment by requiredregistration** [comment]
there should be options for advanced users, that block all requests that don't originate from tabs, if something is requested it will be because the user allowed it explicitly, advanced users will understand that that will break update checking, update downloading, etc.

**Comment by futpib** [comment]
Opening #155 for that

**Comment by requiredregistration** [comment]
the previous pre releases blocked requests that didn't originate from tabs also, that should be brought back

[i was typing this as you were opening issue 155]

**Comment by futpib** [comment]
Well, while we have no UI to control this behaviour brining it back is no use, it will only break most addons and some firefox functionality. Actually, the challenge is not to create a UI, but to trace the requests back to addon that's making it.

**Comment by requiredregistration** [comment]
of course, i meant in combination with the UI

it should be possible
