### ISSUE TITLE
Destination domens is doubled in popup

### ISSUE THREAD

**Issue by Halibut80** [futpib/policeman#110]
<a href="http://lh5.ggpht.com/-zoonsbLIxbk/VKbX3Cm6y8I/AAAAAAAAaWY/I2BUbol8PwU/s0/clipboard.png"><img src="http://lh4.ggpht.com/-ZYBmtYzjoN4/VKbX3vWX2uI/AAAAAAAAaWc/vdzRNr_KS9c/s0/thumb2.jpg" </a>

Policeman 0.17, Win 8.1 x64, Firefox Nightly 37.0a1 x64 BuildID:20150101030214

**Comment by futpib** [comment]
Oh wow, how could I not notice this

**Comment by bastik-tor** [comment]
Maybe because it did not occur in your Firefox version you tested with?

I saw the bug and was curious, but could not reproduce it with FF 34.

**Comment by futpib** [comment]
You saw this on an earlier (<17) version?

**Comment by bastik-tor** [comment]
Either it was clarified or there is a github bug, because I got a notification, but can't see any message here.

"You saw this on an earlier (<17) version?"

No, I did not. I saw issue 110, then decided to update to 0.17 to test if I can reproduce it.

Anyway it should be fixed with 0.17.1
