### ISSUE TITLE
popup dont work after enable Quick Locale Switcher

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman#121]
popup dont work after enable Quick Locale Switcher and even after disable it

https://gist.github.com/heforfree/2d5638965335209e5cbe

**Comment by heforfree** [comment]
installed 0.18pre3 and disabled cookiekeeper and now working.close it

**Comment by futpib** [comment]
I guess since #122 is closed, this should be too, although I didn't look into this issue. Will reopen on request.
