### ISSUE TITLE
Doesn't work in combination with cookiekeeper anymore

### ISSUE THREAD

**Issue by fix0101010** [futpib/policeman#122]
Before the latest update policeman worked perfectly in combination with cookiekeeper (https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper/) but now when i have both of them installed in my browser (Firefox 34.0.5) the buttons for policeman and cookiekeeper stops working.
I can still access the options for both policeman and cookiekeeper via about:addons.

Things i've tried:
Downgrade policeman to 0.16.1 : didn't work
Downgrade cookiekeeper to 1.8.0: didn't work

**Comment by futpib** [comment]
fixed by e0b62a9837f00f5c852c90f70a65fa44506920fb
