### ISSUE TITLE
wrong position for collapsed tree in right to left

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman#124]
![image 1](https://cloud.githubusercontent.com/assets/2247864/5643975/8c786fd2-9673-11e4-8292-917d89913e68.png)

![image 2](https://cloud.githubusercontent.com/assets/2247864/5643978/91e3d2d6-9673-11e4-9cef-cf6069d87de7.png)

**Comment by bastik-tor** [comment]
Is it possible to detect that a right to left language is used?

Otherwise the translator has to change ```popup_children_hidden_marker = ▸``` to ```popup_children_hidden_marker = ◂``` if I understand this issue correctly.

**Comment by futpib** [comment]
I guess this is also about wrong indentation, @heforfree is it?

**Comment by heforfree** [comment]
@bastik-tor  thank you this is my mistake
@futpib  yes it is. i used software localization and it is not visible in it.and i leave it unchanged
i updated it on #101

sorry

**Comment by heforfree** [comment]
all this string updated.
popup_children_hidden_marker
popup_allow_rule
popup_reject_rule
popup_arrow
popup_arrow_with_stroke

https://en.wikipedia.org/wiki/Arrow_%28symbol%29
Leftwards Arrow With Stroke
so if policeman translated to arabic translator should know that
thank you
Leftwards Arrow
