### ISSUE TITLE
Can hostname regex pattern in a rule become more flexible (powerful)?

### ISSUE THREAD

**Issue by stewie** [futpib/policeman#13]
Currently, how would I block (for example) all US hostnames?
/*.us/ is not an acceptable input
/[.]us$/ is not acceptable

Perhaps leading wildcard patterns are impossible to hash, so should not be supported.
But let's please consider another example:

How would I, via a single rule, block all webtrendslive.DOMAIN.TLD ?
/^webtrendslive.*/ is not an acceptable hostname input

As of this patch:
https://github.com/futpib/policeman/commit/ed3e5222882995cfc3374857c1976cb48b0d496f
we are able to supply a (one) IP address.
Ability to whitelist (for instance) 192.168.\* would be quite useful
as would ability to block an entire malware-prevalent subnet (invented example) 69.228.*

Regardless what wildcards might be supported, I'm wishing for availability of a rule which would block (or raise an infobar notice) when an href or xmlhttp requests a numeric IP address, vs a DNS hostname (often practiced by hit-n-run malware distributors).

**Comment by dxdragon** [comment]
@futpib Like this rule as follow
web -> web:
  *.example -> /\d+\.\d+\.\d+\.\d+/: ACCEPT
Then how to limit the content type, e.g. objects?

**Comment by futpib** [comment]
@dxdragon
```
rules:
  web -> web:
    *.example.com -> /\d+.\d+.\d+.\d+/:
      [contentType] (STYLESHEET|IMAGE): ACCEPT
```
[Another example](https://github.com/futpib/policeman-rulesets/blob/24adf432b621b7efe8b6e910a532932fbc40868f/examples/allow_hosts_that_look_like_cdns.ruleset)

**Comment by dxdragon** [comment]
@futpib Yeah, I do write the rule referring to that example before, but it doesn't work, so does above code you provided. just no [contentType], it works.....
