### ISSUE TITLE
suspend on this tab and reject_special_paths

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman#135]
it seems reject_special_paths.ruleset after enable  suspend on this tab option
still working.so it is benefit of this ruleset? or bug?
but if i select suspend operation that ruleset not working

**Comment by futpib** [comment]
"Suspend on tab" is part of "User temporary" ruleset ([wiki has a note on this](https://github.com/futpib/policeman/wiki/Preinstalled-rulesets-description#temporary-rules-added-by-ui)). "Suspend" on the other hand really suspends Policeman.
