### ISSUE TITLE
Many addons are broken

### ISSUE THREAD

**Issue by Halibut80** [futpib/policeman#141]
For now, with 0.18pre7, I dont see favicons on many sites, without any blocked requests in popup. For examples:
<a href="https://lh6.ggpht.com/-S3NfN8bQrC8/VLPps42_b3I/AAAAAAAAaeg/99d5WJDdkds/s0/clipboard2.png"><img src="https://lh4.ggpht.com/-F5dqQM4DhDE/VLPptu9et5I/AAAAAAAAaek/i5UBQJkJf8o/s0/thumb2.jpg"></a>

<a href="https://forum.mozilla-russia.org/index.php">https://forum.mozilla-russia.org/index.php</a>

Maybe need rulesets for that, or "allow same site" and "allow same second level domains" must also allow these type requests?

Also, i have issue with some addons (LastPass, <a href="https://addons.mozilla.org/en-us/firefox/addon/s3google-translator/">S3.Google Translator</a>, HTTPS Everywhere (with enabled "ssl observatory"), NoScript(with enabled ABE), Adblock Plus cannot update subscriptions and other) which displays a message about the the impossibility connect to the server, without any blocked requests showed in Policeman popup. OCSP requests also seems are blocked. Suspend Policeman solved this issues.

**Comment by requiredregistration** [comment]
i can confirm no favicons with wired.com

**Comment by requiredregistration** [comment]
with the stable version the favicon is still requested and downloaded, with the nightly build they are not
