### ISSUE TITLE
YouTube does not work without "-> [Chrome destination]" rule

### ISSUE THREAD

**Issue by requiredregistration** [futpib/policeman#142]
for example, going directly to any youtube video [for example, https://www.youtube.com/watch?v=KWZGAExj-es], doesn't always show [Chrome destination] in the popup so that it can be allowed temporarily or permanently

![untitled](https://cloud.githubusercontent.com/assets/6291226/5715326/ea646e1e-9adf-11e4-9e9d-f63380ae669c.png)

**Comment by futpib** [comment]
It only shows up when a request was attempted to it, why do you expect to see it on youtube?

**Comment by requiredregistration** [comment]
the video file will not be downloaded if that is not allowed

**Comment by requiredregistration** [comment]
for testing, by going to www.youtube.com, [Chrome destination] is always available to allow temporarily or permanently, but by going back directly to a video it is not

i was testing with a nightly build, with the stable version it seems that it happened only once

**Comment by futpib** [comment]
I wonder how can chrome destination be involved on any youtube page. I think the real issue here is a conflict with youtube and that it somehow depends on chrome destination.

**Comment by requiredregistration** [comment]
later today, the next stable version, 35, will be released, once it is released, i'll test again

with the nightly build and dailymotion [for example, http://www.dailymotion.com/video/x2ek14c_long-distance-runner-spinning-top_tech], allowing [Chrome destination] is not required for the video file to be requested for its download to start

**Comment by requiredregistration** [comment]
nothing has changed, there is still a problem

it's HTML5 video, it has something to do with that

**Comment by heforfree** [comment]
@requiredregistration 
without rule that highlighted in  screenshot right after i click play video
i get"an error  accoured...please try again later"
then i can see [Chrome destination] after some second and i see it is allowed
![image1](https://cloud.githubusercontent.com/assets/2247864/5794315/87d9da84-9f7d-11e4-8530-d47c8efecc2e.png)


![image2](https://cloud.githubusercontent.com/assets/2247864/5794316/91d415f4-9f7d-11e4-8c37-0b9918c56dd4.png)

and with 3 unhighlighted rule and just with allow youtube to googlevideo.com
every video will play fine for me

**Comment by chrisbura** [comment]
`Chrome destination` shows up if an iframe has an empty `src`. If so, the browser will default to `about:blank` as the `src` which will cause the request.

If a blocked script or resource dynamically sets the `src` then the browser will end up making a request to `Chrome destination` since the `src` remains unset.

**Comment by requiredregistration** [comment]
hovering over the search bar causes [Chrome destination] to appear on the popup list

**Comment by futpib** [comment]
This should work since 2c0df48be70a6555aa2a488536bb5cebc9fd5d53 (0.19pre0).

**Comment by Maxxee** [comment]
The odd thing is that on YouTube video pages [Chrome destination] is ALWAYS shown in green, there are never blocked objects - but still it *has to be* allowed explicitly.
