### ISSUE TITLE
Some rulesets require a browser restart to apply/disable

### ISSUE THREAD

**Issue by Halibut80** [futpib/policeman#149]
After enabling "HTTPS sandbox" ruleset, image from hosting in the persistent whitelist (and does not supporting https) does not blocked after page refresh (I set "HTTPS sandbox" higher priority position in list of rulesets, than persistent rules), only after browser restart. Same after disabling "HTTPS sandbox" ruleset.

Policeman 0.18pre6

**Comment by bastik-tor** [comment]
I am unable to reproduce this with 0.18pre9.

@Halibut80 Did you click on "Save" at the bottom of the ruleset list after rearranging or enabling/disabling rulesets?

**Comment by Halibut80** [comment]
Oh, sorry.., I forgot about "save".

**Comment by bastik-tor** [comment]
@futpib Can you think of some indicator to notify the user that he might want to save changes he made to the ruleset list? Something non-intrusive that helps to prevent errors like this one. Would be bad if people believe Policeman is broken.

**Comment by futpib** [comment]
@bastik-tor It saves automatically when tab is closed (or another prefs subpage opened)

**Comment by futpib** [comment]
Oh, I got it. Maybe it should just apply new setting immediately on change leaving only "Undo" button. Anyway, I don't think it's a big deal.

**Comment by Halibut80** [comment]
@futpib New firefox preferences "in-content" apply settings after changes, this is why i forgot about need to click on save button. Apply new setting immediately on change - good deal, I agree.

**Comment by Halibut80** [comment]
Also, this is need to unification interface with Nightly https://github.com/futpib/policeman/issues/123
