### ISSUE TITLE
log in 0.18pre9

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman#151]
https://gist.github.com/heforfree/0ee55326062e4a8d6377

**Comment by heforfree** [comment]
go to about:addons then click policeman options

**Comment by heforfree** [comment]
one other,
https://gist.github.com/heforfree/8b91b69d138525166634

**Comment by futpib** [comment]
Opened #152 for about:policeman.

How do I reproduce the other one?

**Comment by heforfree** [comment]
i see in origin, chrome origin and in destination,chrome destination
i click chrome destination and see image and style request allowed.
but when i click style i am not able  to see request list.
but on same site i again refreshed page but dont see chrome origin to chrome destination
just see chrome origin to same site

**Comment by futpib** [comment]
142f1e40bf8c1f0f244057b257847112914f1c8d

**Comment by futpib** [comment]
cbe4ccde8278d1a6a6abd1150cae8de516764f2c
