### ISSUE TITLE
popup menu is not displayed correctly in policeman .18

### ISSUE THREAD

**Issue by excalibur1234** [futpib/policeman#159]
i just installed policeman 0.18 and now my popup menu is only partially displayed:
http://imagizer.imageshack.com/img907/2087/scPAqB.png
i can still click all buttons (even if i do not see them) in the popup menu. tool tips, etc. seems to work, too.

i use firefox 35 on linux. the popup menu of policeman .17.x was fine.

**Comment by ozar** [comment]
futpib fixed this issue already with Policeman 0.18.1

**Comment by futpib** [comment]
same as #157
