### ISSUE TITLE
[Feature Request] Rules for redirected pages

### ISSUE THREAD

**Issue by aimtsou** [futpib/policeman#161]
It would be great if we could add a ruleset in a way that we can avoid certain urls and go directly on them. IE:

www.xxxxx.com/id=number
and when you click on the video to get id=number&vid=number and proceed this page instead of the one which goes through the redirection

**Comment by futpib** [comment]
Like instead of following through a redirects chain **a**→**b**→**c** you want to go right **a**→**c**? I don't really get your point, but if that's it, it is not possible because it would require some kind of prediction on where would **b** lead, which is not possible in general without loading **b** first.

**Comment by Halibut80** [comment]
I also want similar feature: integrated in Policeman redirect cleaner. Like <a href="https://github.com/diegocr/CleanLinks">diegocr/CleanLinks · GitHub</a>, or Redirect Cleaner (deleted for some reason from AMO by auhtor), but this is goes beyond the scope of Policeman mission and require, probably, a lot of work.

**Comment by futpib** [comment]
If that the proposed thing, it's not something that fits into policeman's purpose.

**Comment by aimtsou** [comment]
I want with a ruleset defined, while clicking on b and is detected by
ruleset to go directly to c. Isn't that possible?

**Comment by futpib** [comment]
@aimtsou Sounds like what CleanLinks does, It's a nice feature but it does not fit well into what policeman is doing.

**Comment by aimtsou** [comment]
I thought this would be nice because especially some sites with videos have
certain video ads so that could be a nice workaround. But anyway thanks for
your feedback
