### ISSUE TITLE
Policeman won't work after Firefox profile moved

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman#162]
i used below method  and move profile folder to ramdisk.then policeman dont work
https://www.raymond.cc/blog/superspeed-firefox-by-putting-profile-and-sqlite-database-in-ramdisk/
here log
https://gist.github.com/heforfree/518f07d70c57d8641921

**Comment by futpib** [comment]
@heforfree As a quick solution I can suggest removing `extensions.policeman.manager.installedPathsByIds` from `prefs.js` in your profile

**Comment by heforfree** [comment]
yes working :+1:
