### ISSUE TITLE
GUI issues when URIs are too long

### ISSUE THREAD

**Issue by scadu** [futpib/policeman#165]
I noticed that Policeman doesn't handle very well long requests' URIs.
First example: buttons on the right are invisible – https://i.imgur.com/Bx3jxas.jpg
Second: popup is taking up whole screen width – https://i.imgur.com/I4BXk68.jpg
With more addresses popup could be as big as browser's window, I was kinda baffled seeing this.
And here you can see correct behaviour: https://i.imgur.com/jbkf8KW.jpg

Would be great if popup had one size and shorten URIs to n signs, like µmatrix for example.

Policeman 0.18.1, Firefox 35.0.1 running on Linux.

**Comment by futpib** [comment]
I think this was fixed in course of fixing #40, I can't reproduce it anymore.

**Comment by scadu** [comment]
Yup, looks like problems with window manager. Seems to be working now.
