### ISSUE TITLE
installed rulest not fully scrollable

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman#174]
as you can see error not in scroll
![image1](https://cloud.githubusercontent.com/assets/2247864/6007520/13346ad2-ab30-11e4-8cf1-48a527cc5089.png)

and  allow_redirects_same_site.ruleset dont work on google
if Same site and Same base domain ruleset enabled it ask me for google to example.com redirect
also with disabled Same site and Same base domain it ask me for google to example.com redirect
but with just enabled allow_redirects_same_site.ruleset it dont ask me

**Comment by futpib** [comment]
Opened futpib/policeman-rulesets#7 for *allow_redirects_same_site.ruleset*.
