### ISSUE TITLE
same color if first allow second level domain

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman#175]
as you can see i first allow request to s3.feedly.com
but same site has blocked request but it is green
![image2](https://cloud.githubusercontent.com/assets/2247864/6010429/8e3566c0-ab47-11e4-8377-bbb508cc113b.png)

**Comment by futpib** [comment]
@heforfree I have no idea what you think is going wrong on this screenshot

**Comment by heforfree** [comment]
@futpib it most get lower green color or something
![8e3566c0-ab47-11e4-8377-bbb508cc113b](https://cloud.githubusercontent.com/assets/2247864/6164050/6f8dd49a-b2af-11e4-889d-978d60a108d7.png)

**Comment by futpib** [comment]
It's 70/2 so it's mostly green
