### ISSUE TITLE
Have reject rules be stronger than allow

### ISSUE THREAD

**Issue by 5boro** [futpib/policeman#193]
It would be nice if policeman would treat reject rules over allow rules, that way if a website is asking for a lot of sources you could just reject the unwanted sources and allow everything else.

![](http://nn.lv/olcq) 

For exemple in this picture every podcast is getting requested from it's own source, so I'd like to **reject google analytics** and **allow everyhing else**. 

In the current state, **allow everything** takes over **reject google analytics**.

**Comment by heforfree** [comment]
in about:policeman#rulesets-manager disable "Reject any request" ruleset and it is  change to
allow any request then you must create rject rule.
and even you can put it in blacklist ruleset (currently not fully working)
https://github.com/futpib/policeman-rulesets

**Comment by heforfree** [comment]
and about screenshot i see you have temp rule,your reject rule dont work because order of ruleset
you can reorder by drag and drop in manage rulsets in preferences of policeman
