### ISSUE TITLE
Wrong target url(content type?)

### ISSUE THREAD

**Issue by Halibut80** [futpib/policeman#198]
I'm not sure what is this, but open http://game238770.konggames.com/gamez/0023/8770/live/index.html (html5 game) and see:
<img src="https://lh3.googleusercontent.com/-lu2jBNhC7Jo/VVE4eCSHQtI/AAAAAAAAa8w/OvfgW2LAd5Y/s0/clipboard2.png" border=0><br/>&nbsp;<br/>

NoScript shows:<code> blob:</code> in his menu.

Win 8.1 x64, Firefox Nightly 40.0a1 x64 BuildID: 20150510030207 (e10s disabled), Policeman 0.19pre1

**Comment by futpib** [comment]
Looks like the page actually calls http://undefined/
![devtools/network](https://cloud.githubusercontent.com/assets/4330357/7659031/c8d24942-fb47-11e4-951a-f7a0bf3910dd.png)
