### ISSUE TITLE
Pale Moon Support

### ISSUE THREAD

**Issue by beerisgood** [futpib/policeman#204]
Can we please have Pale Moon support? Mozilla destroy Firefox addons more and more so the future is Pale Moon ;)

**Comment by Bfgeshka** [comment]
Agree. Please, make policerman compatible with palemoon.

**Comment by futpib** [comment]
Sorry, that's a wontfix [#18#issuecomment-61978871](https://github.com/futpib/policeman/issues/18#issuecomment-61978871) (though I would happily accept a contribution towards fixing this issue).

**Comment by myrdd** [comment]
futpib wrote:

> I am not against supporting older Firefoxes, like if someone would implement that and issue a pull request (one could adapt Adblock's CustomizableUI shim or something like that), I would happily merge that, but I won't put effort into this, sorry.

In case someone wants to implement non-Australis support, RequestPolicy's code might be helpful:

* [JavaScript code](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta10/src/content/main/window-manager-toolbarbutton.js), 
* [CSS file](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta10/src/skin/toolbarbutton.css) – different selectors are needed for Australis/non-Australis

**Comment by vitaminx** [comment]
Hi, I'd love to synchronize my Policeman rules between several computers - I use unison (like rsync), but I can't find the files where the Policeman rules are stored.
There's a directory called "~/.mozilla/firefox/default/policeman/rulesets" but it's empty.
Which files do I need to synchronize? Where does Policeman store it's rules?
Thanks.
