### ISSUE TITLE
Typo in https://github.com/futpib/policeman/wiki/Help page

### ISSUE THREAD

**Issue by RichardWilliamPearse** [futpib/policeman#211]
It is a BAD idea:

It is ~~not~~ a bad idea to allow "chrome -> anywhere" and "anywhere -> chrome" unless you are really careful about every single request. *The d*~~D~~efault ruleset already allows some requests from chrome (absolutely necessary ones, like page loadings, and some others for compatibility with other addons).

It is NOT a bad idea:

It is not a bad idea to allow "chrome -> anywhere" and "anywhere -> chrome" ~~unless~~ *if* you are really careful about every single request. *The d*~~D~~efault ruleset already allows some requests from chrome (absolutely necessary ones, like page loadings, and some others for compatibility with other addons).

**Comment by futpib** [comment]
Isn't our wiki open for editing?

**Comment by CrisBRM** [comment]
@futpib Just checked and you're right. Oh boy.

**Comment by RichardWilliamPearse** [comment]
ah, yes, silly me. I'll change it.

Cheers.


|
> Isn't our wiki open for editing?


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/futpib/policeman/issues/211#issuecomment-112953468
