### ISSUE TITLE
Content types for refresh and popup

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman#57]
CSP types for refresh and Popup
actually there is addon "Pop-up Controller",i want policeman do the same thing so i can manage in one addon
https://addons.mozilla.org/en-US/firefox/addon/pop-up-control/

also for refresh there is addon "RefreshBlocker" its block refreshing page when noscript can not block
that refresh type
https://addons.mozilla.org/en-US/firefox/addon/refreshblocker/

thank you

**Comment by futpib** [comment]
Won't fix because Firefox handles popups well out-of-box and neither popup nor refresh makes sense as a content type.
