### ISSUE TITLE
I cannot make it work with YouTube html5 player

### ISSUE THREAD

**Issue by ghost** [futpib/policeman#78]
![ythtml5](https://cloud.githubusercontent.com/assets/886325/5235292/a689e17e-77f8-11e4-94e1-b8dc6e658450.png)

There is one "request rejected", but no "destination". How to unblock?

**Comment by BrianGilbert** [comment]
I have it working with the following rules and flash uninstalled from my computer:
```
Allow requests for anything from www.youtube.com to [any domain]
```
plus these additional persistent rules
```
Reject requests for anything from www.youtube.com to pagead2.googlesyndication.com
Reject requests for anything from www.youtube.com to googleads.g.doubleclick.net
Reject requests for anything from www.youtube.com to ads.doubleclick.net
```

**Comment by anonish** [comment]
i have the following settings and i just tested them on html5 youtube and it works (I disabled viewtube which is my preferred method on youtube)
```
Allow requests for [anything] from www.youtube.com to [www.youtube.com]
Allow requests for [media] from www.youtube.com to [googlevideo.com]
Allow requests for [anything] from www.youtube.com to [ytimg.com]
```
these two next ones may not be needed, but they are useful for avatars and comments:
```
Allow requests for [images] from www.youtube.com to [yt3.ggpht.com] 
Allow requests for [frames] from www.youtube.com to [plus.googleapis.com]
```
the latter requries
```
allow requests for images from [plus.googleapis.com] to [ssl.gstatic.com]
allow requests for images from [plus.googleapis.com] to [googleusercontent.com]
```
i block everything by default and this seems to work well (and certainly works with viewtube)
