### ISSUE TITLE
Script blocking not working(?)

### ISSUE THREAD

**Issue by Devices** [futpib/policeman#93]
It appears that everything is blocked in the settings, javascript can still be executed.
If you click on the button on the site http://www.bom.gov.au/australia/radar/about/clickme.shtml it tries to run javascript and it displays text if it does. See: http://i.imgur.com/vyfuy7l.png
if you disable javascript in about:config no such text appears.

same thing happens for other javascript tests such as http://isjavascriptenabled.com/ or http://ip-check.info/?lang=en

There is some discussion on the technology board on 4chan about this issue, which can be viewed here: https://archive.rebeccablacktech.com/g/thread/S45677062#p45681092

**Comment by Halibut80** [comment]
@futpib Maybe I'm wrong (my knowledge of English is as bad, as in programming), but maybe <a href="https://dvcs.w3.org/hg/content-security-policy/raw-file/tip/csp-specification.dev.html#script-src">this</a> means that inline scripts can be blocked from loading by resources of the Policeman, with new CSP 1.1 specification?
